mysql:
  db: loc
  host: localhost
  password: 123456
  port: 3306
  user: root

redis:
  host: localhost
  port: 6379
  db: 0
  password: ""


secret: secret
serve_static: true

server:
  http_port: 8094
  https_port: 8095
  cert_file: ""
  key_file: ""

system:
  general:
    backend: ""
  mail:
    host: ""
    port: 465
    username: ""
    password: ""
    from: ""
  search:
    endpoint: https://duckduckgo-api.vercel.app
    query: 5
